FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install --include=dev

COPY . .

CMD ["npx", "nodemon", "--watch", "src", "--ext", "ts,json", "--exec", "node", "--loader", "ts-node/esm", "src/index.ts"]