version: '3.9'

services:
  backend:
    container_name: backend-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      # use Dockerfile.dev for dev mode
    ports:
      - '5001:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/app-db
      - JWT_SECRET=supersecurekey
    volumes:
      - .:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
